# Generated by Django 4.1 on 2022-10-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fullname', models.CharField(max_length=64)),
                ('phonenumber', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
