# Generated by Django 4.1 on 2022-10-10 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='artical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('discription', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('picture', models.CharField(blank=True, max_length=3000)),
                ('date', models.CharField(default=datetime.date(2022, 10, 10), max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
