# Generated by Django 4.1 on 2022-10-11 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_artical_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='date',
            field=models.CharField(default=datetime.date(2022, 10, 11), max_length=64),
        ),
        migrations.AlterField(
            model_name='artical',
            name='discription',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='artical',
            name='picture',
            field=models.CharField(blank=True, max_length=9999999999),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.CharField(blank=True, max_length=9999999999),
        ),
    ]
