# Generated by Django 4.1 on 2022-10-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_artical_date_alter_artical_discription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='publication/')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=5000)),
                ('url', models.URLField(max_length=2097152)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='artical',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
