# Generated by Django 4.1 on 2022-10-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='title',
            field=models.CharField(default='untitled', max_length=100),
        ),
        migrations.AddField(
            model_name='media',
            name='url',
            field=models.URLField(blank=True, default='', max_length=2097152),
        ),
    ]
