# Generated by Django 4.1 on 2022-10-18 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_artical_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullname',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='nan', max_length=64),
        ),
        migrations.AlterField(
            model_name='artical',
            name='date',
            field=models.CharField(default=datetime.date(2022, 10, 18), max_length=64),
        ),
    ]
