# Generated by Django 4.1 on 2022-10-19 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_fullname_user_firstname_user_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='date',
            field=models.CharField(default=datetime.date(2022, 10, 19), max_length=64),
        ),
    ]
