# Generated by Django 4.1 on 2022-10-24 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_artical_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='date',
            field=models.CharField(default=datetime.date(2022, 10, 24), max_length=64),
        ),
    ]
