# Generated by Django 4.1 on 2022-10-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_aprea_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprea_memberships',
            name='organization_logo',
            field=models.ImageField(blank=True, default=False, upload_to='organization_logo/'),
        ),
    ]
