# Generated by Django 4.1 on 2022-10-25 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_aprea_memberships_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='artical',
            name='date',
            field=models.CharField(default=datetime.date(2022, 10, 25), max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=5000000000),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=1100000),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, upload_to='user/'),
        ),
    ]
