# Generated by Django 4.1 on 2022-11-08 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_firstname_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='license_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_province', models.CharField(max_length=20)),
                ('lc_city', models.CharField(max_length=78)),
                ('lc_area', models.CharField(max_length=599)),
                ('lc_name', models.CharField(max_length=200)),
                ('lc_contact_no', models.CharField(max_length=20)),
                ('lc_address', models.CharField(max_length=999)),
                ('lc_website', models.CharField(max_length=1000)),
                ('lc_logo', models.ImageField(blank=True, upload_to='Comapny/logo/')),
                ('lc_secp', models.ImageField(blank=True, upload_to='Company/doc/SECP')),
                ('lc_letter', models.ImageField(blank=True, upload_to='Company/doc/letter')),
                ('lc_exprience', models.ImageField(blank=True, upload_to='Company/doc/exprience')),
            ],
        ),
        migrations.CreateModel(
            name='license_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_person', models.CharField(max_length=90)),
                ('lp_full_name', models.CharField(max_length=128)),
                ('lp_last_name', models.CharField(max_length=128)),
                ('lp_cnic', models.CharField(max_length=15)),
                ('lp_date_expiry', models.CharField(max_length=10)),
                ('lp_date_birth', models.CharField(max_length=10)),
                ('lp_email', models.EmailField(max_length=254, unique=True)),
                ('lp_address', models.CharField(max_length=999)),
                ('lp_phone', models.CharField(max_length=20)),
                ('lp_job_type', models.CharField(blank=True, max_length=99)),
                ('lp_person_img', models.ImageField(blank=True, upload_to='license/lp_profile_img/')),
                ('lp_cnic_front', models.ImageField(blank=True, upload_to='license/cnic/')),
                ('lp_cnic_back', models.ImageField(blank=True, upload_to='license/cnic/')),
            ],
        ),
        migrations.AlterField(
            model_name='artical',
            name='date',
            field=models.CharField(default=datetime.date(2022, 11, 8), max_length=64),
        ),
    ]
