# Generated by Django 4.1 on 2022-11-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_artical_comments_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical_comments',
            name='user_image',
            field=models.CharField(blank=True, max_length=999999999999),
        ),
    ]
